"""empty message

Revision ID: 0aa1b9fd913a
Revises: ed1d86e63c59
Create Date: 2016-08-22 22:52:25.259073

"""

# revision identifiers, used by Alembic.
revision = '0aa1b9fd913a'
down_revision = 'ed1d86e63c59'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fbcase', sa.Column('sstatus', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fbcase', 'sstatus')
    ### end Alembic commands ###
