"""2016-08-03 02:22:23.099077 add role to auth_user

Revision ID: 15fb98bfa2bc
Revises: 7e9c27853468
Create Date: 2016-08-03 02:22:23.099077

"""

# revision identifiers, used by Alembic.
revision = '15fb98bfa2bc'
down_revision = '7e9c27853468'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('role', sa.String(length=32), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'role')
    ### end Alembic commands ###
