"""2016-08-20 05:36:49.736039 add ixpriority to fbcase

Revision ID: 24cc0e0e92f6
Revises: 09739cd28592
Create Date: 2016-08-20 05:36:49.736039

"""

# revision identifiers, used by Alembic.
revision = '24cc0e0e92f6'
down_revision = '09739cd28592'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fbcase', sa.Column('ixpriority', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fbcase', 'ixpriority')
    ### end Alembic commands ###
