"""2018-12-21 10:01:55.758090 set fbcase.milestone_excluded not nullable

Revision ID: 347dacc87134
Revises: f3e100d0d38d
Create Date: 2018-12-21 10:01:55.758090

"""

# revision identifiers, used by Alembic.
revision = '347dacc87134'
down_revision = 'f3e100d0d38d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fbcase', 'milestone_excluded',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fbcase', 'milestone_excluded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###
