"""2016-08-20 05:49:41.848140 drop table milestone_cateogry, add milestone to category

Revision ID: 462c7c3864b5
Revises: 24cc0e0e92f6
Create Date: 2016-08-20 05:49:41.848140

"""

# revision identifiers, used by Alembic.
revision = '462c7c3864b5'
down_revision = '24cc0e0e92f6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milestone_category')
    op.add_column('category', sa.Column('milestone', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'category', 'milestone', ['milestone'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'milestone')
    op.create_table('milestone_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'milestone_category_pkey')
    )
    ### end Alembic commands ###
