"""2016-09-19 20:29:00.730920 set invoice.customer_id not nullable, add invoice_id to milestone

Revision ID: 526c6d50e42f
Revises: 8d6c273042dd
Create Date: 2016-09-19 20:29:00.730920

"""

# revision identifiers, used by Alembic.
revision = '526c6d50e42f'
down_revision = '8d6c273042dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('milestone', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'milestone', 'invoice', ['invoice_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'milestone', type_='foreignkey')
    op.drop_column('milestone', 'invoice_id')
    op.alter_column('invoice', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
