"""2018-11-18 05:39:28.661730 add ixpersonassignedto to fbcase, add status to fogbugzusercase

Revision ID: 57c76677278c
Revises: bcf206e90fde
Create Date: 2018-11-18 05:39:28.661730

"""

# revision identifiers, used by Alembic.
revision = '57c76677278c'
down_revision = 'bcf206e90fde'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fbcase', sa.Column('ixpersonassignedto', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fbcase', 'fogbugzuser', ['ixpersonassignedto'], ['ixperson'])
    op.add_column('fogbugzusercase', sa.Column('status', sa.String(length=20), nullable=False, server_default='Unset'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fogbugzusercase', 'status')
    op.drop_constraint(None, 'fbcase', type_='foreignkey')
    op.drop_column('fbcase', 'ixpersonassignedto')
    ### end Alembic commands ###
