"""2016-08-05 14:45:34.013739 change fogbugz-proper column names to lowercase

Revision ID: 5c8ad242f237
Revises: 6069019bd714
Create Date: 2016-08-05 14:45:34.013739

"""

# revision identifiers, used by Alembic.
revision = '5c8ad242f237'
down_revision = '6069019bd714'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():

    op.drop_constraint(u'fbcase_ixPersonResolvedBy_fkey', 'fbcase', type_='foreignkey')
    op.drop_constraint(u'fbcase_ixFixFor_fkey', 'fbcase', type_='foreignkey')
    op.drop_constraint(u'fogbugzusercase_ixPerson_fkey', 'fogbugzusercase', type_='foreignkey')
    op.drop_constraint(u'fogbugzusercase_ixBug_fkey', 'fogbugzusercase', type_='foreignkey')
    op.drop_constraint(u'milestone_ixProject_fkey', 'milestone', type_='foreignkey')

    op.drop_constraint(u'fogbugzuser_ixPerson_key', 'fogbugzuser', type_='unique')
    op.drop_constraint(u'milestone_ixFixFor_key', 'milestone', type_='unique')
    op.drop_constraint(u'project_ixProject_key', 'project', type_='unique')
    op.drop_constraint(u'fbcase_ixBug_key', 'fbcase', type_='unique')

    op.drop_column('fbcase', 'sTitle')
    op.drop_column('fbcase', 'ixBug')
    op.drop_column('fbcase', 'ixPersonResolvedBy')
    op.drop_column('fbcase', 'ixFixFor')
    op.drop_column('fogbugzuser', 'sFullname')
    op.drop_column('fogbugzuser', 'ixPerson')
    op.drop_column('fogbugzuser', 'fRate')
    op.drop_column('fogbugzusercase', 'ixPerson')
    op.drop_column('fogbugzusercase', 'fHours')
    op.drop_column('fogbugzusercase', 'ixBug')
    op.drop_column('milestone', 'bPaid')
    op.drop_column('milestone', 'sFixFor')
    op.drop_column('milestone', 'bFrozen')
    op.drop_column('milestone', 'fPaidAmount')
    op.drop_column('milestone', 'bInvoiced')
    op.drop_column('milestone', 'fInvoiceAmount')
    op.drop_column('milestone', 'dtPaid')
    op.drop_column('milestone', 'ixFixFor')
    op.drop_column('milestone', 'dtStart')
    op.drop_column('milestone', 'ixProject')
    op.drop_column('project', 'ixProject')

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fbcase', sa.Column('ixbug', sa.Integer(), nullable=True))
    op.add_column('fbcase', sa.Column('ixfixfor', sa.Integer(), nullable=True))
    op.add_column('fbcase', sa.Column('ixpersonresolvedby', sa.Integer(), nullable=True))
    op.add_column('fbcase', sa.Column('stitle', sa.String(length=255), nullable=False))
    op.add_column('fogbugzuser', sa.Column('frate', sa.Float(), nullable=False))
    op.add_column('fogbugzuser', sa.Column('ixperson', sa.Integer(), nullable=True))
    op.add_column('fogbugzuser', sa.Column('sfullname', sa.String(length=255), nullable=False))
    op.add_column('fogbugzusercase', sa.Column('fhours', sa.Float(), nullable=False))
    op.add_column('fogbugzusercase', sa.Column('ixbug', sa.Integer(), nullable=True))
    op.add_column('fogbugzusercase', sa.Column('ixperson', sa.Integer(), nullable=True))
    op.add_column('milestone', sa.Column('bfrozen', sa.Boolean(), nullable=True))
    op.add_column('milestone', sa.Column('binvoiced', sa.Boolean(), nullable=True))
    op.add_column('milestone', sa.Column('bpaid', sa.Boolean(), nullable=True))
    op.add_column('milestone', sa.Column('dtpaid', sa.DateTime(), nullable=True))
    op.add_column('milestone', sa.Column('dtstart', sa.DateTime(), nullable=True))
    op.add_column('milestone', sa.Column('finvoicedamount', sa.Float(), nullable=True))
    op.add_column('milestone', sa.Column('fpaidamount', sa.Float(), nullable=True))
    op.add_column('milestone', sa.Column('ixfixfor', sa.Integer(), nullable=True))
    op.add_column('milestone', sa.Column('ixproject', sa.Integer(), nullable=False))
    op.add_column('milestone', sa.Column('sfixfor', sa.String(length=255), nullable=False))
    op.add_column('project', sa.Column('ixproject', sa.Integer(), nullable=True))

    op.create_unique_constraint(None, 'fbcase', ['ixbug'])
    op.create_unique_constraint(None, 'fogbugzuser', ['ixperson'])
    op.create_unique_constraint(None, 'milestone', ['ixfixfor'])
    op.create_unique_constraint(None, 'project', ['ixproject'])
    
    op.create_foreign_key(None, 'fogbugzusercase', 'fogbugzuser', ['ixperson'], ['ixperson'])
    op.create_foreign_key(None, 'fogbugzusercase', 'fbcase', ['ixbug'], ['ixbug'])
    op.create_foreign_key(None, 'milestone', 'project', ['ixproject'], ['ixproject'])
    op.create_foreign_key(None, 'fbcase', 'fogbugzuser', ['ixpersonresolvedby'], ['ixperson'])
    op.create_foreign_key(None, 'fbcase', 'milestone', ['ixfixfor'], ['ixfixfor'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('ixProject', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project', type_='unique')
    op.create_unique_constraint(u'project_ixProject_key', 'project', ['ixProject'])
    op.drop_column('project', 'ixproject')
    op.add_column('milestone', sa.Column('ixProject', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('milestone', sa.Column('dtStart', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('milestone', sa.Column('ixFixFor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('milestone', sa.Column('dtPaid', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('milestone', sa.Column('fInvoiceAmount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('milestone', sa.Column('bInvoiced', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('milestone', sa.Column('fPaidAmount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('milestone', sa.Column('bFrozen', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('milestone', sa.Column('sFixFor', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('milestone', sa.Column('bPaid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'milestone', type_='foreignkey')
    op.create_foreign_key(u'milestone_ixProject_fkey', 'milestone', 'project', ['ixProject'], ['ixProject'])
    op.drop_constraint(None, 'milestone', type_='unique')
    op.create_unique_constraint(u'milestone_ixFixFor_key', 'milestone', ['ixFixFor'])
    op.drop_column('milestone', 'sfixfor')
    op.drop_column('milestone', 'ixproject')
    op.drop_column('milestone', 'ixfixfor')
    op.drop_column('milestone', 'fpaidamount')
    op.drop_column('milestone', 'finvoicedamount')
    op.drop_column('milestone', 'dtstart')
    op.drop_column('milestone', 'dtpaid')
    op.drop_column('milestone', 'bpaid')
    op.drop_column('milestone', 'binvoiced')
    op.drop_column('milestone', 'bfrozen')
    op.add_column('fogbugzusercase', sa.Column('ixBug', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fogbugzusercase', sa.Column('fHours', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('fogbugzusercase', sa.Column('ixPerson', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fogbugzusercase', type_='foreignkey')
    op.drop_constraint(None, 'fogbugzusercase', type_='foreignkey')
    op.create_foreign_key(u'fogbugzusercase_ixBug_fkey', 'fogbugzusercase', 'fbcase', ['ixBug'], ['ixBug'])
    op.create_foreign_key(u'fogbugzusercase_ixPerson_fkey', 'fogbugzusercase', 'fogbugzuser', ['ixPerson'], ['ixPerson'])
    op.drop_column('fogbugzusercase', 'ixperson')
    op.drop_column('fogbugzusercase', 'ixbug')
    op.drop_column('fogbugzusercase', 'fhours')
    op.add_column('fogbugzuser', sa.Column('fRate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('fogbugzuser', sa.Column('ixPerson', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fogbugzuser', sa.Column('sFullname', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fogbugzuser', type_='unique')
    op.create_unique_constraint(u'fogbugzuser_ixPerson_key', 'fogbugzuser', ['ixPerson'])
    op.drop_column('fogbugzuser', 'sfullname')
    op.drop_column('fogbugzuser', 'ixperson')
    op.drop_column('fogbugzuser', 'frate')
    op.add_column('fbcase', sa.Column('ixFixFor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fbcase', sa.Column('ixPersonResolvedBy', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fbcase', sa.Column('ixBug', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fbcase', sa.Column('sTitle', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fbcase', type_='foreignkey')
    op.drop_constraint(None, 'fbcase', type_='foreignkey')
    op.create_foreign_key(u'fbcase_ixFixFor_fkey', 'fbcase', 'milestone', ['ixFixFor'], ['ixFixFor'])
    op.create_foreign_key(u'fbcase_ixPersonResolvedBy_fkey', 'fbcase', 'fogbugzuser', ['ixPersonResolvedBy'], ['ixPerson'])
    op.drop_constraint(None, 'fbcase', type_='unique')
    op.create_unique_constraint(u'fbcase_ixBug_key', 'fbcase', ['ixBug'])
    op.drop_column('fbcase', 'stitle')
    op.drop_column('fbcase', 'ixpersonresolvedby')
    op.drop_column('fbcase', 'ixfixfor')
    op.drop_column('fbcase', 'ixbug')
    ### end Alembic commands ###
