"""2018-11-18 23:57:41.131033 add ixperson, status to fogbugzusercase

Revision ID: 78fb000a2836
Revises: d7497deb5f0f
Create Date: 2018-11-18 23:57:41.131033

"""

# revision identifiers, used by Alembic.
revision = '78fb000a2836'
down_revision = 'd7497deb5f0f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fogbugzusercase', sa.Column('ixperson', sa.Integer(), nullable=True))
    op.add_column('fogbugzusercase', sa.Column('status', sa.String(length=20), nullable=False, server_default='Unset'))
    op.create_foreign_key(None, 'fogbugzusercase', 'fogbugzuser', ['ixperson'], ['ixperson'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fogbugzusercase', type_='foreignkey')
    op.drop_column('fogbugzusercase', 'status')
    op.drop_column('fogbugzusercase', 'ixperson')
    ### end Alembic commands ###
