"""empty message

Revision ID: 88dcd9df2c53
Revises: 462c7c3864b5
Create Date: 2016-08-21 03:25:40.493581

"""

# revision identifiers, used by Alembic.
revision = '88dcd9df2c53'
down_revision = '462c7c3864b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('milestone_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'category_milestone_fkey', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'milestone', ['milestone_id'], ['id'])
    op.drop_column('category', 'milestone')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('milestone', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key(u'category_milestone_fkey', 'category', 'milestone', ['milestone'], ['id'])
    op.drop_column('category', 'milestone_id')
    ### end Alembic commands ###
