"""2016-08-05 10:51:48.292119 drop tables project and fogbugzuser

Revision ID: 908a222f4b32
Revises: 15fb98bfa2bc
Create Date: 2016-08-05 10:51:48.292119

"""

# revision identifiers, used by Alembic.
revision = '908a222f4b32'
down_revision = '15fb98bfa2bc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('fogbugzuser')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fogbugzuser',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ixPerson', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sPerson', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('fRate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'fogbugzuser_pkey')
    )
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ixProject', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sProject', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'project_pkey')
    )
    ### end Alembic commands ###
