"""2016-08-05 14:17:22.913533 add dtStart to milestone

Revision ID: 94c9eeb7d570
Revises: cdbf19d8c639
Create Date: 2016-08-05 14:17:22.913533

"""

# revision identifiers, used by Alembic.
revision = '94c9eeb7d570'
down_revision = 'cdbf19d8c639'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('milestone', 'dtStart',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('milestone', 'dtStart',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    ### end Alembic commands ###
