"""empty message

Revision ID: 95814f6dbb4d
Revises: 64cf17d03a3a
Create Date: 2016-08-05 11:01:19.215065

"""

# revision identifiers, used by Alembic.
revision = '95814f6dbb4d'
down_revision = '64cf17d03a3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'case', ['ixBug'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'case', type_='unique')
    ### end Alembic commands ###
