"""2016-08-25 00:01:30.890077 add bcomped to fogbugzusercase

Revision ID: a191fdf88f87
Revises: 948da03336e0
Create Date: 2016-08-25 00:01:30.890077

"""

# revision identifiers, used by Alembic.
revision = 'a191fdf88f87'
down_revision = '948da03336e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fogbugzusercase', sa.Column('bcomped', sa.Boolean(), server_default='f', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fogbugzusercase', 'bcomped')
    ### end Alembic commands ###
