"""empty message

Revision ID: b123e8aba1a1
Revises: 526c6d50e42f
Create Date: 2016-11-04 23:26:52.592670

"""

# revision identifiers, used by Alembic.
revision = 'b123e8aba1a1'
down_revision = '526c6d50e42f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('state', sa.String(length=20), nullable=False, server_default='final'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'state')
    ### end Alembic commands ###
