"""empty message

Revision ID: c38084462f69
Revises: 347dacc87134
Create Date: 2019-02-10 17:49:45.125994

"""

# revision identifiers, used by Alembic.
revision = 'c38084462f69'
down_revision = '347dacc87134'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fbcase', sa.Column('billed_ixpersonresolvedby', sa.Integer(), nullable=True))
    op.drop_constraint(u'fbcase_billed_personresolvedby_fkey', 'fbcase', type_='foreignkey')
    op.create_foreign_key(None, 'fbcase', 'fogbugzuser', ['billed_ixpersonresolvedby'], ['ixperson'])
    op.drop_column('fbcase', 'billed_personresolvedby')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fbcase', sa.Column('billed_personresolvedby', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fbcase', type_='foreignkey')
    op.create_foreign_key(u'fbcase_billed_personresolvedby_fkey', 'fbcase', 'fogbugzuser', ['billed_personresolvedby'], ['ixperson'])
    op.drop_column('fbcase', 'billed_ixpersonresolvedby')
    ### end Alembic commands ###
