"""2018-11-20 02:51:46.588556 drop status from fogbugzusercase

Revision ID: c50c43ab21bc
Revises: 78fb000a2836
Create Date: 2018-11-20 02:51:46.588556

"""

# revision identifiers, used by Alembic.
revision = 'c50c43ab21bc'
down_revision = '78fb000a2836'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fogbugzusercase', 'status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fogbugzusercase', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    ### end Alembic commands ###
