"""empty message

Revision ID: d92ccc4e1540
Revises: 9d43294b905c
Create Date: 2017-12-26 01:37:02.277826

"""

# revision identifiers, used by Alembic.
revision = 'd92ccc4e1540'
down_revision = '9d43294b905c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('deliverable_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'milestone', 'deliverable', ['deliverable_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'milestone', type_='foreignkey')
    op.drop_column('milestone', 'deliverable_id')
    ### end Alembic commands ###
