"""2018-12-21 10:01:15.969143 add milestone_excluded to fbcase, nullable

Revision ID: f3e100d0d38d
Revises: e68fdb448f43
Create Date: 2018-12-21 10:01:15.969143

"""

# revision identifiers, used by Alembic.
revision = 'f3e100d0d38d'
down_revision = 'e68fdb448f43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fbcase', sa.Column('milestone_excluded', sa.Boolean(), nullable=True, server_default='f'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fbcase', 'milestone_excluded')
    ### end Alembic commands ###
