"""2016-08-05 10:58:34.494406 add ixProject to project

Revision ID: f573d87520f3
Revises: 8ba7a2631fe5
Create Date: 2016-08-05 10:58:34.494406

"""

# revision identifiers, used by Alembic.
revision = 'f573d87520f3'
down_revision = '8ba7a2631fe5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'project', ['ixProject'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    ### end Alembic commands ###
